### ISSUE TITLE
Terminal Input Not Visible When Pasting Commands

### ISSUE THREAD

**Issue by nyxb** [Dokploy/dokploy#1127]
## To Reproduce

1. Install and start dokploy
2. Open a new terminal process
3. Type any command manually - input will be visible as expected
4. Copy any command (e.g. `ls -la`) and paste it into the terminal
5. Observe that the pasted command is not visible in the terminal, only the prompt "joyou=#" is shown
6. If you select/highlight the area after the prompt, the pasted text becomes visible
7. Press Enter to execute the pasted command

Make sure to:
- Use a clean dokploy installation
- Test with different commands to paste
- Try both short and long commands

![Image](https://github.com/user-attachments/assets/929a6374-4b69-45b4-9c05-3a4234a83a76)

![Image](https://github.com/user-attachments/assets/a072cd85-7da6-4d66-b769-4b6520b78117)

### Current vs. Expected behavior

When following the steps above:

Expected behavior:
- Both manually typed and pasted commands should be visible in the terminal window
- Users should be able to see and verify the command before execution

Current behavior:
- Manually typed commands are displayed correctly
- Pasted commands are not visible at all
- Only the terminal prompt is shown when pasting content
- The commands still execute but users cannot verify what they're about to run

### Additional context

his appears to be a terminal input handling issue specifically related to pasted content. The issue impacts usability and security since users cannot verify commands before execution. The terminal seems to process the input differently based on whether it's typed or pasted.

**Comment by 2003Aditya** [comment]
@Siumauricio can i work on this issue ?

**Comment by Siumauricio** [comment]
Yes @2003Aditya

**Comment by biati-digital** [comment]
Not sure if related but when using light mode the terminal text is completely invisible, you need to select to be able to see the text

![Image](https://github.com/user-attachments/assets/3eeec152-71f9-4e51-a923-24261a8acb72)

![Image](https://github.com/user-attachments/assets/7dacd89d-fca7-412f-9f25-1b428812828d)

To replicate

![Image](https://github.com/user-attachments/assets/57077001-7992-4b79-a25f-0617c290b5dd)

**Comment by Siumauricio** [comment]
> Not sure if related but when using light mode the terminal text is completely invisible, you need to select to be able to see the text
> 
> ![Image](https://github.com/user-attachments/assets/3eeec152-71f9-4e51-a923-24261a8acb72)
> 
> ![Image](https://github.com/user-attachments/assets/7dacd89d-fca7-412f-9f25-1b428812828d)
> 
> To replicate
> 
> ![Image](https://github.com/user-attachments/assets/57077001-7992-4b79-a25f-0617c290b5dd)

I tested in the current version and is working fine 

![Image](https://github.com/user-attachments/assets/c145f355-4721-4fa1-b76a-98ba77147224)

**Comment by Siumauricio** [comment]
Fixed in #1203

**Comment by biati-digital** [comment]
@Siumauricio for me the error happens with Safari, I just updated and the error persist. Works correctly in edge.
