### ISSUE TITLE
Traefik not working properly upon restart

### ISSUE THREAD

**Issue by maelp** [Dokploy/dokploy#1802]
### To Reproduce

If I do a `sudo reboot` on my server, everything restarts at launch, but I can't access Dokploy on my "external" DNS (eg dokploy.myhost.com),

I need to do `ssh -L 3000:localhost:3000 my-server`
then go to http://localhost:3000 and login to Dokploy
then go to "Webserver > Reload webserver"

and then everything starts working

do you know where it could come from? Would there be a way to automate this upon restart?

### Current vs. Expected behavior

It should work when rebooting the server and having all the processes restarted

### Provide environment information

```bash
Linux box with latest Dokploy
```

### Which area(s) are affected? (Select all that apply)

Traefik

### Are you deploying the applications where Dokploy is installed or on a remote server?

Same server where Dokploy is installed

### Will you send a PR to fix it?

Yes

**Comment by RicardoPBarbosa** [comment]
I also got a similar issue after a power outage. When I turned my server on again, I could not access the dokploy dashboard and my deployed apps, both via their https domains and directly via my public IP address + 3000.
I ran some tests to check if it was an issue with my router, but pings to my public IP are getting through.
Accessing dokploy in the local network, I can see the following Traefik log:
`
ERR Unable to obtain ACME certificate for domains error="cannot get ACME client get directory at 'https://acme-v02.api.letsencrypt.org/directory': Get \"https://acme-v02.api.letsencrypt.org/directory\": dial tcp 172.65.32.248:443: connect: no route to host" ACME CA=https://acme-v02.api.letsencrypt.org/directory acmeCA=https://acme-v02.api.letsencrypt.org/directory domains=["dokploy.myserver.com"] providerName=letsencrypt.acme routerName=dokploy-router-app-secure@file rule=Host('dokploy.myserver.com')
`

**Comment by andrekutianski** [comment]
I have a similar issue, but it crashes when I try to map more than one additional port in Traefik on the Server options. Traefik completely goes offline, and the only way to access it is on non-SSL port 3000. 

When I return to the dashboard using port 300 to remove the additional port, the modal doesn't show any port. I click on save and reload traefik, and voilà, it goes up again.

PS: adding an additional port also to remove any existing environment variables existing the traefik settings.

**Comment by unleashit** [comment]
Also trying to troubleshoot a somewhat related issue. I also noticed Dokploy wasn't reachable after a server reboot, but all other containers were fine. I restarted the Traefik container through the CLI and at that point it was online again. But then I noticed a Dokploy update was available (from 0.21.7 to 0.21.8), so I went ahead with it without a lot of thought thinking perhaps it might have a fix. But something went wrong and the browser lost the connection during the process and this time restarting the containers didn't fix.

I've tried a few things: roll Dokploy back to 0.21.7, throw out all containers and do a new Dokploy install using the latest install script (reusing the same volumes and /etc/dokploy) , but so far no good, Dokploy isn't reachable (either through https://domain or port 3000). Dokploy logs seem OK, but Traefik has some errors that sound related to permissions and/or label issues:

<details>
<summary>Traefik logs</summary>

``
2025-05-02T09:17:38Z ERR error="accept tcp [::]:8080: use of closed network connection" entryPointName=traefik
2025-05-02T09:17:38Z ERR error="accept tcp [::]:80: use of closed network connection" entryPointName=web
2025-05-02T09:17:38Z ERR error="close tcp [::]:80: use of closed network connection" entryPointName=web
2025-05-02T09:17:38Z ERR error="accept tcp [::]:443: use of closed network connection" entryPointName=websecure
2025-05-02T09:17:38Z ERR error="close tcp [::]:8080: use of closed network connection" entryPointName=traefik
2025-05-02T09:17:39Z ERR error="close tcp [::]:443: use of closed network connection" entryPointName=websecure
2025-05-02T09:17:39Z ERR Failed to list containers for docker error="Get \"http://%2Fvar%2Frun%2Fdocker.sock/v1.24/containers/json\": context canceled" providerName=docker
2025-05-02T09:17:39Z ERR Cannot retrieve data error="context canceled" providerName=docker
2025-05-02T09:25:37Z ERR Router nextcloud-nextcloud-w4csgm-7-websecure cannot be linked automatically with multiple Services: ["nextcloud-nextcloud-w4csgm-8-web" "nextcloud-nextcloud-w4csgm-8-websecure"] providerName=docker routerName=nextcloud-nextcloud-w4csgm-7-websecure
``
</details>

The nextcloud error is weird but I don't think it's the cause, as this error still appears even after shutting down the NC container an restarting Traefik. It looks like Dokploy at some point incremented the volume names from 7 to an 8 for some reason. I have manually added labels with w4csgm-7 in the docker compose, because that was what Dokploy originally generated... and it worked until now.

<details>
<summary>Dokploy logs</summary>

```
> dokploy@v0.21.8 start /app
> node -r dotenv/config dist/server.mjs

Default middlewares already exists
Network is already initilized
Main config already exists
Default traefik config already exists
{
  severity_local: 'NOTICE',
  severity: 'NOTICE',
  code: '42P06',
  message: 'schema "drizzle" already exists, skipping',
  file: 'schemacmds.c',
  line: '132',
  routine: 'CreateSchemaCommand'
}
{
  severity_local: 'NOTICE',
  severity: 'NOTICE',
  code: '42P07',
  message: 'relation "__drizzle_migrations" already exists, skipping',
  file: 'parse_utilcmd.c',
  line: '207',
  routine: 'transformCreateStmt'
}
Migration complete
Setting up cron jobs....
```
</details>

Before these issues, I hadn't recently changed anything in Dokploy (or even on the server except to update).

**Comment by andrekutianski** [comment]
> Also trying to troubleshoot a somewhat related issue. I also noticed Dokploy wasn't reachable after a server reboot, but all other containers were fine. I restarted the Traefik container through the CLI and at that point it was online again. But then I noticed a Dokploy update was available (from 0.21.7 to 0.21.8), so I went ahead with it without a lot of thought thinking perhaps it might have a fix. But something went wrong and the browser lost the connection during the process and this time restarting the containers didn't fix.
> 
> I've tried a few things: roll Dokploy back to 0.21.7, throw out all containers and do a new Dokploy install using the latest install script (reusing the same volumes and /etc/dokploy) , but so far no good, Dokploy isn't reachable (either through https://domain or port 3000). Dokploy logs seem OK, but Traefik has some errors that sound related to permissions and/or label issues:
> 
> Traefik logs
> The nextcloud error is weird but I don't think it's the cause, as this error still appears even after shutting down the NC container an restarting Traefik. It looks like Dokploy at some point incremented the volume names from 7 to an 8 for some reason. I have manually added labels with w4csgm-7 in the docker compose, because that was what Dokploy originally generated... and it worked until now.
> 
> Dokploy logs
> Before these issues, I hadn't recently changed anything in Dokploy (or even on the server except to update). Also, Traefik seems to be working OK as I can still connect to other containers (definitely not a firewall or network problem).

This also happened to me after an update. Try this on cli:
```
docker service scale dokploy=0
docker service scale dokploy=1
```

**Comment by unleashit** [comment]
Thanks comrade, tried scaling down and back up again but didn't do it for me.

**Comment by andrekutianski** [comment]
> Thanks comrade, tried scaling down and back up again but didn't do it for me.

another approach: scale down to 0 (zero), check dokploy images that you my have and try to remove any without tagging. To conclude rome dokploy image with latest tag and manually update `curl -sSL https://dokploy.com/install.sh | sh -s update`

**Comment by unleashit** [comment]
Definitely need to get off my _ and brush up on both Swarm and Traefik, but I'll try that later when I have time. I actually modded that install script at first to specifically install the 0.21.7 tag, but I didn't first delete :latest or verify that I didn't end up with .8. I'll try that!

**Comment by unleashit** [comment]
Tried clean installing (clean except config and volumes) the last 3 versions of Dokploy to no avail. Bad gateway every time, including curl http://localhost:3000. 

I'm sure a totally clean install would work, but I'm not quite ready to take that step yet. TBH, I'm considering moving on from Dokploy, as this has made me realize the problems one can get into in having a wrapper dependency around Traefik. Granted, I shot myself in the foot by initially deleting all of my containers trying to troubleshoot, not really considering that I needed Dokploy working to regenerate them with the proper hashed names, etc.

**Comment by maelp** [comment]
@unleashit did you try just clicking the "reload" button in the "webserver" panel on the dashboard?

To reinstall is quite easy, just do a backup of /etc/dokploy for the config, and of the postgres database, and you should be good

**Comment by maelp** [comment]
To avoid loss of data with volumes, etc, I try to just mount them as folders rather than use volumes, so at least it's me who control where they are and how they work, it worked nicely so far

**Comment by unleashit** [comment]
> did you try just clicking the "reload" button in the "webserver" panel on the dashboard?

I'm not able to get to the dashboard. Doesn't this button just restart the traefik container (same as docker restart <traefik.)? I've done that, as well as reboot the server, etc.

> To avoid loss of data with volumes, etc, I try to just mount them as folders rather than use volumes

I used to do that until I learned performance of named volumes is much better (this may only affect frequently accessed files, but I prefer to have everything end up on one place in the file system). But for me, this isn't a problem with data loss. It's that Dokploy renames volume and container names from docker compose files. So in the case that Dokploy goes down and isn't easily recoverable, you can't just run docker compose up on the exist yml files to get your services back up. You need to edit them all (I have about 15) and ensure the right volume names with the Dokploy hash are there or it will create brand new volumes. I knew this ahead of time, but being human I forgot and it was quite the struggle...

**Comment by maelp** [comment]
@unleashit I'm not exactly sure what the button does, but to access it, just do a SSH tunnel from your host to your laptop, eg

```sh
ssh -L 3000:localhost:3000 myuser@myhost
```

this will open a SSH connection to your host, and tunnel the port 3000 there to the port 3000 on your localhost

then you can just go in a browser on your laptop and go to http://localhost:3000 and you will access the interface

**Comment by malko** [comment]
Same problem here, seems the traefik container is just missing, when going through the dokploy interface trying to show logs from traefik shows 0 container and no logs. Perhaps something related to the automatic docker cleanup and not automatically pulling image ?

**Comment by maelp** [comment]
For me I can confirm that I need to indeed go to "reload traefik" after a reboot for things to start working again

**Comment by maelp** [comment]
And indeed it seems because either the traefik container is missing, or not "connected" to Dokploy, since when looking at logs, it just doesn't find any corresponding containers for Traefik

**Comment by unleashit** [comment]
@maelp Thanks again, but I think my problem might a bit different than everyone else's. For me, Traefik is working fine, but I can't access Dokploy. Yes I've tried connecting directly to port 3000 (both using a local port forward and just curl http://localhost:3000) and it won't connect. I probably should file a separate issue, but since several people are having issues after recently updating, it may be related. For me the issue is connecting to Dokploy, not Traefik, which is connecting all my other apps just fine.

**Comment by maelp** [comment]
And for some reason, after a Traefik reload, everything works correctly, except ownCloud infinite scale that I somehow need to restart / reload manually for it to work (it shows as "restarted" automatically after a reboot, but when trying to connect to it from my owncloud.server.com it doesn't find it, and after a restart of the container it works)

Here's my config

```yaml
version: "3.7"

# Check https://fariszr.com/owncloud-infinite-scale-docker-setup/
services:
  ocis:
    image: owncloud/ocis:7.1.2
    user: 0:0
    ports:
      - 127.0.0.1:9200:9200
    entrypoint:
      - /bin/sh
    # run ocis init to initialize a configuration file with random secrets
    # it will fail on subsequent runs, because the config file already exists
    # therefore we ignore the error and then start the ocis server
    command: ["-c", "ocis init || true; ocis server"]
    environment:
      OCIS_URL: https://owncloud.mydomain.com
      OCIS_LOG_LEVEL: info
      OCIS_LOG_COLOR: true
      OCIS_LOG_PRETTY: true
      PROXY_TLS: false
      OCIS_INSECURE: true
      IDM_ADMIN_PASSWORD: ${IDM_ADMIN_PASSWORD}
      SETTINGS_GRPC_ADDR: 0.0.0.0:9191
      GATEWAY_GRPC_ADDR: 0.0.0.0:9142 # make the REVA gateway accessible to the app drivers
      # PROXY_TLS is set to "false", the download url has no https
      STORAGE_USERS_DATA_GATEWAY_URL: http://ocis:9200/data
      THUMBNAILS_FILESYSTEMSTORAGE_ROOT: /var/lib/ocis-thumbnails
      # basic auth (not recommended, but needed for eg. WebDav clients that do not support OpenID Connect, like some iOS apps)
      PROXY_ENABLE_BASIC_AUTH: true
    volumes:
      - /mnt/data/owncloud-ocis/ocis.yaml:/etc/ocis/ocis.yaml
      - /mnt/data/owncloud-ocis/data:/var/lib/ocis
      - /mnt/data/owncloud-ocis/thumbnails:/var/lib/ocis-thumbnails
```

**Comment by maelp** [comment]
@unleashit indeed your issue might be different then

**Comment by malko** [comment]
I decided to relaunch the traefik container as a service instead of a simple docker run -d as optionally proposed on the documentation for manual install. I bumped the traefik version to 3.3 which should not cause problem with the way dokploy use it. Here's the command:
```
docker service create \
     --name dokploy-traefik \
     --constraint 'node.role==manager' \
     --network dokploy-network \
     --mount type=bind,source=/etc/dokploy/traefik/traefik.yml,target=/etc/traefik/traefik.yml \
     --mount type=bind,source=/etc/dokploy/traefik/dynamic,target=/etc/dokploy/traefik/dynamic \
     --mount type=bind,source=/var/run/docker.sock,target=/var/run/docker.sock \
     --publish mode=host,published=443,target=443 \
     --publish mode=host,published=80,target=80 \
     --publish mode=host,published=443,target=443,protocol=udp \
     traefik:v3.3
``` 

For now it seems to work properly

**Comment by maelp** [comment]
nice! @Siumauricio perhaps a way to fix the issue by using this in the install script?

@malko so to make this work from an existing deployment we should kill the traefik container and then start your service right?

```sh
docker ps | grep -i traefik
# find the id
docker container stop CONTAINER_ID && docker container rm CONTAINER_ID
# start the service
docker service create \
     --name dokploy-traefik \
     --constraint 'node.role==manager' \
     --network dokploy-network \
     --mount type=bind,source=/etc/dokploy/traefik/traefik.yml,target=/etc/traefik/traefik.yml \
     --mount type=bind,source=/etc/dokploy/traefik/dynamic,target=/etc/dokploy/traefik/dynamic \
     --mount type=bind,source=/var/run/docker.sock,target=/var/run/docker.sock \
     --publish mode=host,published=443,target=443 \
     --publish mode=host,published=80,target=80 \
     --publish mode=host,published=443,target=443,protocol=udp \
     traefik:v3.3
```

I'm trying this and I will report

**Comment by Siumauricio** [comment]
This issue may be related since we removed the initialization when the dokploy container restarts, it is likely that some people are still running traefik as a service and not as a standalone container which was the change we made, if you really have problems recreate the container as it is in the install command:

```
    docker run -d \
        --name dokploy-traefik \
        --network dokploy-network \
        --restart always \
        -v /etc/dokploy/traefik/traefik.yml:/etc/traefik/traefik.yml \
        -v /etc/dokploy/traefik/dynamic:/etc/dokploy/traefik/dynamic \
        -v /var/run/docker.sock:/var/run/docker.sock \
        -p 80:80/tcp \
        -p 443:443/tcp \
        -p 443:443/udp \
        traefik:v3.1.2
```

**Comment by maelp** [comment]
@Siumauricio so you're saying we should NOT run as a service right?

But the issue still happens for me in both cases (service or not)

**Comment by Siumauricio** [comment]
If you still have problems, check the traefik container logs. 

```docker logs dokploy-traefik```

or if you have troubles to access to dokploy ui

check the logs also

```docker service logs dokploy```

**Comment by maelp** [comment]
@Siumauricio 

![Image](https://github.com/user-attachments/assets/dc5c9639-8ec3-4185-8823-408b7c28fb0b)

**Comment by Siumauricio** [comment]
I see nothing wrong, 

what exactly you can't do?

are you using applications, compose or templates ?

**Comment by maelp** [comment]
@Siumauricio Seems a lot of errors though, no? are those "normal errors"? for now, none of the templates are reachable from eg karakeep.mydomain.com or whatever (it shows 404 or Bad gateway etc)

I'm going to try to do a full reload with "Restart webserver" in the interface to see

**Comment by Siumauricio** [comment]
@maelp just redeploy again and it should work

**Comment by maelp** [comment]
@Siumauricio you mean "reboot the instance" ? or just go to Dashboard > Webserver > Reload webserver?

for now this is what I've been doing to fix the issue, but the point of this issue is that we would expect that after a `sudo reboot` on my host with Dokploy, everything comes back up and works again, but so far it seems traefik requires a reload after rebooting the host

**Comment by maelp** [comment]
@Siumauricio 

Okay just did a `sudo reboot`, now Dokploy is available after reboot at `dokploy.myserver.com`, and other services too, except owncloud (not sure why) which I need to manually reboot

**Comment by malko** [comment]
@Siumauricio I was just about modifying my comment about using traeffik as a swarm service instead of single container I see that dokploy doesn't play well with it as a swarm service. 
But the problem still exists, after a reboot with a standalone traefik instance (after an OS update) the traefik container was just missing and so it wasn't reloaded making services unavailable. This is perhaps not directly related to dokploy, but perhaps we could imagine a way to relaunch pull / reload the traefik container if not available on the system.

**Comment by maelp** [comment]
@Siumauricio hmmm... re-creating the container as you mentioned worked for a while, but after a few "sudo reboot" it stopped working again, and I have to do the same as before (SSH tunnel to :3000, access the interface locally, reload Traefik)

**Comment by Siumauricio** [comment]
It seems that I found the issue, the strange thing is that it didn't happen in hetzner instances, but in DO I was able to reproduce this problem, it seems that the dokploy-network network as it is in overlay swarm mode, dokploy-traefik being a standalone container is probably not able to connect so it won't be able to get up and will have this error 


```
Error: ‘failed to set up container networking: could not find a network matching network mode dokploy-network: network dokploy-network not found
```

one solution I tried and it worked for me is 

first remove the traefik container completely and run this command in this sequence 

```
    docker run -d
        --name dokploy-traefik \
        --restart always
        -v /etc/dokploy/traefik/traefik.yml:/etc/traefik/traefik.yml \ \
        -v /etc/dokploy/traefik/dynamic:/etc/dokploy/traefik/dynamic
        -v /var/run/docker.sock:/var/run/docker.sock \
        -p 80:80/tcp \
        -p 443:443/tcp \
        -p 443:443/udp -p 443:443/udp
        traefik:v3.1.2

# Join manually to the network
docker network connect dokploy-network dokploy-traefik
```

Let me know if that helps and I can update the installation script

@maelp @malko

**Comment by maelp** [comment]
I will try (PS: I'm using Hetzner too, and I had the issue)

**Comment by maelp** [comment]
The correct command would be (you were missing some backslashes)

```sh
docker run -d \
        --name dokploy-traefik \
        --restart always \
        -v /etc/dokploy/traefik/traefik.yml:/etc/traefik/traefik.yml \
        -v /etc/dokploy/traefik/dynamic:/etc/dokploy/traefik/dynamic \
        -v /var/run/docker.sock:/var/run/docker.sock \
        -p 80:80/tcp \
        -p 443:443/tcp \
        -p 443:443/udp -p 443:443/udp \
        traefik:v3.1.2
```

**Comment by maelp** [comment]
@Siumauricio Followed your instructions, then did `sudo reboot`:

- Dokploy restarted, and I can access it through dokpoloy.myserver.com (that's good)
- Other services restarted but when trying to access them externally through traefik it loops endlessly and does "Gateway timeout"

logs:

![Image](https://github.com/user-attachments/assets/44c9fb9e-d534-4992-9381-e7a08cfdd444)

if I do a "reload traefik" in the interface it seems to loop forever and does nothing (and doesn't solve the issue)

**Comment by maelp** [comment]
Tried to do a "reload server" on the webserver page, Dokploy is still accessible on https://dokploy.myserver.com, but none of the apps are accessible on their external url (myapp.myserver.com) although they are running since I see notifications in the backgroud

**Comment by Siumauricio** [comment]
did you redeployed the services?

**Comment by maelp** [comment]
@Siumauricio I just did a "sudo reboot", do I need to redeploy services first? (I'd assume they would be "auto-redeployed" upon reboot?)

**Comment by Siumauricio** [comment]
Since we have been changing things related to networks, please redeploy your services and check that you can access them, then you can test reboot and see if your services are accessible.

**Comment by malko** [comment]
will try the `docker network connect dokploy-network dokploy-traefik`, but also what is weird is trying to enable the traefik dashboard just remove the container and doesn't restart it here's the logs: 

![Image](https://github.com/user-attachments/assets/b450f3c4-d129-4587-992c-d9870f438553)

I can confirm that when asking for enabling dashboard traefik was running and all services were reachable. After running this no more traefik container even looking at it with docker ps

**Comment by maelp** [comment]
@Siumauricio :
- did your fix (created the traefik container, joined swarm manually)
- went through all services to redeploy them
- did a sudo reboot
- now all services are accessible

so indeed we need to go manually to all services and click "redeploy" first to "fix them" (not sure why this isn't done "automatically" upon reboot?)

**Comment by maelp** [comment]
(and it seems to have fixed my issue with ownCloud infinite scale not restarting at boot for some reason)

**Comment by Siumauricio** [comment]
yes the first step is to recreate the dokploy-traefik and then join the network manually

then go to all the applications, templates and so on and do a redeploy manually

then to test you can restart your server and everything should work.

**Comment by malko** [comment]
didn't need the docker network command as I've used the following run command:
```
docker run -d \
        --name dokploy-traefik \
        --network dokploy-network \
        --restart always \
        -v /etc/dokploy/traefik/traefik.yml:/etc/traefik/traefik.yml \
        -v /etc/dokploy/traefik/dynamic:/etc/dokploy/traefik/dynamic \
        -v /var/run/docker.sock:/var/run/docker.sock \
        -p 80:80/tcp \
        -p 443:443/tcp \
        -p 443:443/udp \
        traefik:v3.1.2

```
Which already include the `--network dokploy-network`

**Comment by Siumauricio** [comment]
It looks like the same thing, but it's not really the same thing.

using the literal network parameter will try to connect to the network after it is created, instead the 2 approach I shared above is basically create the container and then join the network, it's like it does the 2 things separately it's something related to post-creation.

**Comment by malko** [comment]
Ok finally The problem related to trying to enable dashboard was me still using a 3.3 version of traefik => using 3.1.2 this is working !

**Comment by maelp** [comment]
@Siumauricio hmmmmm on another instance that I have, I tried doing the same and it doesn't work, the "traefik container" logs are empty, no container shown

![Image](https://github.com/user-attachments/assets/f568d5a9-e48e-4558-8fa4-d18fa57ef467)

and when I try to recreate the docker as you showed it says this:

```sh
docker: Error response from daemon: driver failed programming external connectivity on endpoint dokploy-traefik (3b613453133357d558b2fc98dc18e5de69e515b21a246fa5d113164588c34d5b): failed to bind port 0.0.0.0:443/udp: Error starting userland proxy: listen udp4 0.0.0.0:443: bind: address already in use.
```

**Comment by maelp** [comment]
I'm not sure what else than Dokploy could be listening there, as this is literally the only code running on that instance (besides the apps that I'm running *through* Dokploy)

**Comment by maelp** [comment]
Ah the error comes from the fact that there was a duplicate "-p 443" on my commandline

**Comment by maelp** [comment]
Okay it seems to be working now for the other instance

**Comment by Siumauricio** [comment]
Fixed in this commit https://github.com/Dokploy/website/commit/f94ed01222551d14cf35d69fa6d1301301837339

**Comment by Siumauricio** [comment]
the issue was in the installation script fixed in https://github.com/Dokploy/dokploy/issues/1802

**Comment by unleashit** [comment]
For me, the network suggestion didn't fix. I ended up having to do a fresh install, deleting the database and /etc/doploy. While my issue was that dokploy (not traefik) wasn't reachable, the problem started in the same way as the OP (plus had the same Traefik errors as some of the others). But the difference came after updating dokploy to the latest version (I think 0.27.8), Dokploy crashed during the process and I was never able to get it back up. I tried a lot of things, including deleting all docker containers, networks and images (but saving volumes) and using the stock install script. I'm pretty convinced something in either my Traefik config or the Dokploy database was incompatible with the latest updates. Again, I haven't touched anything in the past couple weeks. Just updated, and poof.

Hopefully I'm the only one like this! It's now all up again, but it was a lot of work.

**Comment by Code-Divine** [comment]
Why is this closed when it's not fixed? I reported it again #4057 Maybe the issue was reintroduced?

**Comment by Siumauricio** [comment]
Root cause for this class of failure was found and documented in https://github.com/Dokploy/dokploy/issues/4057#issuecomment-5230237907 — dynamic `docker network connect` attachments (used by isolated deployments) don't survive an ungraceful reboot. That comment includes a corrected recovery command (the old workaround recreates the fragile state).
