### ISSUE TITLE
Image not pulled on docker swarm

### ISSUE THREAD

**Issue by YMS-GBH** [Dokploy/dokploy#1998]
### To Reproduce

1- create application
2- set docker provider (without password)
3- chose registery on advanced settings
4- deploy

### Current vs. Expected behavior

current
Container stuck on "ready". When docker inspect the service and the failed container i got this:
"Status": {
            "Timestamp": "2025-06-03T21:02:26.535000442Z",
            "State": "rejected",
            "Message": "preparing",
            "Err": "No such image: registry.gitlab.myapp.com/web-transverse/project/frontend/frontend:develop-latest",
            "ContainerStatus": {
                "ContainerID": "",
                "PID": 0,
                "ExitCode": 0
            },
            "PortStatus": {}
        },

Expected:
image pulled and deployed on node

### Provide environment information

```bash
OS: ubuntu 24.04
Dokploy v0.22.7
```

### Which area(s) are affected? (Select all that apply)

Docker, Application

### Are you deploying the applications where Dokploy is installed or on a remote server?

Remote server

### Additional context

i look inside the code, the bug come probably from this file: packages/server/src/utils/builders/index.ts

const getAuthConfig = (application: ApplicationNested) => {
	const { registry, username, password, sourceType, registryUrl } = application;

	if (sourceType === "docker") {
		if (username && password) {
			return {
				password,
				username,
				serveraddress: registryUrl || "",
			};
		}
	} else if (registry) {
		return {
			password: registry.password,
			username: registry.username,
			serveraddress: registry.registryUrl,
		};
	}

	return undefined;
};

instead of

const getAuthConfig = (application: ApplicationNested) => {
	const { registry, username, password, sourceType, registryUrl } = application;

	if (sourceType === "docker") {
		if (username && password) {
			return {
				password,
				username,
				serveraddress: registryUrl || "",
			};
		} else if (registry) {
      		        return {
      			        password: registry.password,
      			        username: registry.username,
      			        serveraddress: registry.registryUrl,
      		        };
      	        }
        }
	return undefined;
};

### Will you send a PR to fix it?

No

**Comment by YMS-GBH** [comment]
![Image](https://github.com/user-attachments/assets/c6b04efe-5d2b-4afa-9e52-61e72803e463)
setting up the registry here don't work

**Comment by djsisson** [comment]
@YMS-GBH 

```registry.gitlab.myapp.com/web-transverse/project/frontend/frontend:develop-latest```

can you check your image name, as i don't think this is a valid image name for a repository, you can only have 1 ```/``` either side the repository name such as

```myregistry.com/myrepo/myimage:latest```

if your service is deployed you can always run the following to update it

```docker service update SERVICENAME --image myregistry.com/myrepo/myimage:latest --with-registry-auth```

**Comment by YMS-GBH** [comment]
i tried mannualy to pull my image (locally) it work,
I want to automatise to used it with pull request.
If it's deployed on the dokployUI server it work, the problem is only on the swarm node
@djsisson

**Comment by djsisson** [comment]
does the above swarm mode command work for you, if you use your service name and image name?

**Comment by YMS-GBH** [comment]
its give me
image myregistry.com/myrepo/myimage:latest  could not be accessed on a registry to record
its digest. Each node will access registry.gitlab.infobam.com/web-transverse/panorama/frontend/frontend:develop-latest independently,
possibly leading to different nodes running different
versions of the image.

overall progress: 0 out of 1 tasks 
1/1: preparing [=================================>                 ] 
service update paused: update paused due to failure or early termination of task qmoz6zqus5ws63fzsok48fp35
@djsisson

**Comment by YMS-GBH** [comment]
RE:

My app get deployed only if i put my cred inside the provider

**Comment by djsisson** [comment]
can you run docker login registry.gitlab.infobam.com

you will need your username and PAT key

**Comment by YMS-GBH** [comment]
when i do docker login on the manager, it work for all
@djsisson

**Comment by YMS-GBH** [comment]
doing a docker pull is a temporary solution, but maybe it can be better if dokploy share between all the node all the registry credentials

**Comment by djsisson** [comment]
the docker stack deploy command is missing --with-registry-auth so the registry credentials are not passed on to any nodes, meaning they can't pull any images

https://github.com/Dokploy/dokploy/blob/9c19b1efa33be896bcb85bfd398dd69c128b7a5e/packages/server/src/utils/builders/compose.ts#L179

**Comment by YMS-GBH** [comment]
if i make a "docker login" on the master and i give the credentials on the app it work

**Comment by Paillat-dev** [comment]
Having the same issue since I recently updated, lmk if I can help with debugging

**Comment by YMS-GBH** [comment]
@Paillat-dev il i put the registry credentials in docker providers settings, and make a manual docker login on the server it work.
But there is still an issue because it doesn't use the registry credentials in "advanced" tab

**Comment by Paillat-dev** [comment]
Fair enough, although that's really not practical when I have a multi node cluster, especially if I want it to deploy to *any* node

**Comment by djsisson** [comment]
some did make a pr to fix this #1854 but it got closed

you might be able to run ```docker service update <service_name> --with-registry-auth``` this would then update the service and pass along the registry details to any nodes the service get deployed to

**Comment by Siumauricio** [comment]
Can you try if the latest version fix your issue? I fixed issue related to this

**Comment by YMS-GBH** [comment]
there is still an issue: "No such image: myregister.com/image"

![Image](https://github.com/user-attachments/assets/014fbbb8-d08e-4db1-8ff4-b17c0c3152a9)

![Image](https://github.com/user-attachments/assets/08943b78-880e-469d-9e2e-957f0b8ba0d8)

**Comment by Paillat-dev** [comment]
Same, I am also getting this with public images.

**Comment by ptan01001** [comment]
we facing an issue as well, just easy to fix
go to the Advanced tab
Modify the Run Command like that

```
stack deploy -c docker-compose.yml app-jtmbyq --prune --with-registry-auth
```

**Comment by Paillat-dev** [comment]
Why closed ?

**Comment by YMS-GBH** [comment]
@Paillat-dev because of the fix given by @ptan01001

**Comment by Paillat-dev** [comment]
I don't feel like that's a fix really but whatever
